Modif program startup api ok
Quince-ENI/auto-mate pull request #23
Opened 2023-08-31 13:05 UTC by IlyesJyl

Correction API
Ajouts de nouvelles routes
Ajouts de tests DB et Controleur

2023-08-31 13:12 UTC, CorentinCathe requested changes

2023-08-31 13:13 UTC, IlyesJyl commented on QA-back/Controllers/CarController.cs
> +        // GET: Car
J'ai juste modifié et tout mit au singulier (comme les tables)

2023-08-31 18:35 UTC, IlyesJyl reviewed
Pour moi tout est ok ou alors je ne vois pas les conflits ...

2023-09-01 07:09 UTC, CorentinCathe reviewed
Un max de conflit à régler

2023-09-01 11:11 UTC, merged