feat:conf
Quince-ENI/auto-mate pull request #38
Opened 2023-09-03 16:29 UTC by pebcake

2023-09-03 22:44 UTC, jack-corentin requested changes

2023-09-03 22:44 UTC, jack-corentin commented on prod/docker-prod.yml
> +      - ConnectionStrings:DefaultConnection=server=automatebdd;port=3306;database=automatebdd;user=automate;password=cY4xLFsxbj3frQCKDogqkMBDGLEb47f6mf8biaYN;
Password en dur dans la conf ? Pas possible de faire une variable d'env ?

2023-09-04 09:59 UTC, pebcake commented on prod/docker-prod.yml
> +      - ConnectionStrings:DefaultConnection=server=automatebdd;port=3306;database=automatebdd;user=automate;password=cY4xLFsxbj3frQCKDogqkMBDGLEb47f6mf8biaYN;
done

2023-09-04 10:00 UTC, CorentinCathe approved these changes

2023-09-04 14:45 UTC, merged